### ISSUE TITLE
Double check if app crashes when putInDFU is called while the stone is in setup mode.

### ISSUE THREAD

**Issue by AlexDM0** [crownstone/bluenet-lib-android#6]
Tracking down a bug Anne found, the app seems to crash just after or before the downloading of new firmware. I found a bug in the app that did not communicate the state to the user correctly when putting in DFU. On iOS I saw the issue where I could not continue if the stone is in setup mode and the app thinks it is in normal mode. To test, call the bridge method "putInDFU" on a setup stone.

**Comment by vliedel** [comment]
Fixed in version 0.9.2
